-- Local development seed data.
--
-- Runs automatically after migrations on `pnpm db:reset` (config.toml → [db.seed]).
-- Intentionally empty for now: every table is user-owned and keyed to auth.users,
-- so meaningful seeds need a local auth user to hang off. Add fixtures here when
-- local development of courses / calendar / documents needs them, and keep them
-- idempotent (`on conflict do nothing`) so repeated resets stay clean.
--
-- Never seed production data or anything derived from the real ICS feed.
--
-- Seeds keyed to a REAL account live in ./seed/ instead, and are applied by hand
-- against the linked project. They must not be added to `sql_paths`: they
-- hardcode a user_id from the linked project's auth.users, so `db reset` against
-- a fresh local database would fail on the auth.users foreign key. See
-- ./seed/README.md.
