-- Gate 1 F4 and F3, both closed structurally (M1 item 5e).
--
-- ============================================================================
-- 1. F4 — document_chunks has no unique key at all
-- ============================================================================
--
-- `topic_sources` carries `unique (topic_id, document_id)` and its own migration calls
-- that "the idempotency key for re-processing (§7)". `document_chunks` shipped with only a
-- primary key on a generated uuid, which is not a key over anything real: it makes every
-- INSERT succeed, including the second identical one.
--
-- That is not hypothetical here. `process-document` runs `retries: 3`, and Wave 4's gate 2
-- exercised four real attempts on one document. A chunk step that re-runs after a transient
-- failure inserts the whole document's chunks a second time, and duplicated chunks are
-- worse than wasted rows: `match_chunks` orders by distance and returns the top k, so N
-- copies of one passage crowd out N-1 genuinely different passages. Retrieval quietly gets
-- narrower while the table gets bigger, and nothing errors.
--
-- ── Why the hash now covers the locator as well as the content ──────────────
--
-- The obvious key is `(document_id, chunk_hash)` over the existing content-only hash. It
-- has a silent-loss failure mode that this project specifically exists to avoid: a deck
-- that repeats a slide verbatim (a section divider, a recurring framework diagram) produces
-- two chunks with identical text and therefore identical hashes, and the unique index would
-- drop the second one along with its page-12 citation. The user would be told the deck was
-- fully covered while one of its pages was silently unciteable.
--
-- So `chunk_hash` is redefined as sha256 over the locator AND the normalized content. Two
-- consequences, both intended:
--   * a re-run still produces identical hashes, because the chunker is deterministic and
--     the locator is derived from page numbers — so §7 idempotency holds, which is the
--     property F4 actually asks for;
--   * embedding reuse across *runs* is preserved, and reuse across two identical pages of
--     one document is given up. That saving is a rounding error at $0.02/MTok; a dropped
--     citation is not.
--
-- Partial indexes rather than one index, because the two `source` values have different
-- owners: `document_id` is null for a synthesized topic-page chunk and `topic_id` is null
-- for a document chunk, and NULLs never conflict in a unique index — so a single
-- `(document_id, chunk_hash)` index would leave topic-page chunks entirely unconstrained,
-- which is the same hole in a smaller room.

create unique index if not exists document_chunks_document_identity_key
  on public.document_chunks (document_id, chunk_hash)
  where source = 'document';

create unique index if not exists document_chunks_topic_identity_key
  on public.document_chunks (topic_id, chunk_hash)
  where source = 'topic_page';

comment on column public.document_chunks.chunk_hash is
  'sha256 over the chunk''s locator AND its normalized content. Two jobs: (a) the §7 idempotency key — with the partial unique indexes on (document_id, chunk_hash) and (topic_id, chunk_hash) it makes a re-run of the chunk step a no-op rather than a duplicate insert; (b) the embedding-reuse key across runs — an unchanged hash means the stored vector can be carried over instead of re-billed. The locator is folded in so that a verbatim-repeated slide keeps both of its citations rather than being deduplicated down to one.';

-- ============================================================================
-- 2. F3 — exam_reviews let a user rewrite its own AI provenance stamp
-- ============================================================================
--
-- Gate 1 left this open as a design call. **The call: exam_reviews is an immutable
-- artifact, and its UPDATE policy becomes `using (false)`** — the same treatment
-- `topic_revisions` and `document_processing_events` already have, and for the same reason.
--
-- The reasoning, stated so it can be argued with later:
--
--   * The row carries the §3 five-column stamp (`prompt_id`, `prompt_version`, `provider`,
--     `model`, `input_hash`). That stamp's entire value is that it says what actually
--     produced the content sitting next to it. A user-facing UPDATE policy over the whole
--     row means the client can rewrite the stamp while leaving the content, which converts
--     an audit trail into a field of user-supplied text that merely looks like one. This is
--     the exact falsification `using (false)` was applied against on the other two tables;
--     leaving it open here would make that a coincidence rather than a rule.
--   * There is nothing legitimate to update. Gate 1 already ruled that `exam_reviews` gets
--     no `updated_at` because a review is regenerated by INSERTing a new row, not by
--     editing the old one — so the table was already designed as append-only, and the
--     permissive policy was the part that disagreed with the design.
--   * `stale` is a *derived* flag, computed by comparing `topic_snapshot` against current
--     topic revisions. It is written by the staleness job through the admin client, which
--     is RLS-exempt, so tightening the user-facing policy costs that writer nothing. A user
--     flipping `stale` by hand would be editing a cache of a computation, and the next run
--     would overwrite them anyway.
--
-- Cost of being wrong: if a genuine user-initiated edit to a review is ever wanted, it
-- arrives as a Server Action with its own authorisation, or as a new row. Neither needs
-- this policy. Cost of leaving it: a forgeable provenance stamp on the most expensive
-- artifact the product generates.

drop policy if exists "Users can update own exam reviews" on public.exam_reviews;

create policy "Exam reviews are never updated"
  on public.exam_reviews
  for update
  to authenticated
  using (false)
  with check (false);

comment on table public.exam_reviews is
  'Generated exam reviews (§9). Append-only from a client''s point of view: regeneration INSERTs a new row rather than editing one, so there is deliberately no updated_at and the UPDATE policy is `using (false)` — the row carries the §3 provenance stamp and a rewritable stamp is not a stamp. The `stale` flag is derived and maintained by the background staleness job through the admin client.';
