"use client";

import { DOCUMENT_MIME_TYPES } from "@study/core";
import { Upload } from "tus-js-client";
import { env } from "@/env";
import { createClient } from "@/lib/supabase/client";
import { DOCUMENTS_BUCKET, safeStorageFilename, TUS_CHUNK_BYTES } from "./paths";

/**
 * The browser half of the upload: hash, then push the bytes straight to Storage.
 *
 * ## Why the bytes never touch a Vercel function
 *
 * A Server Action's request body is capped at **4.5 MB**. The real corpus has
 * decks of 9, 19, 25, 40 and 47 MB, so proxying uploads through our own backend
 * does not merely degrade for large files — it fails outright for most of them.
 * The client therefore talks to Supabase Storage directly, authenticated by the
 * user's own access token (so Storage RLS still applies, and still enforces that
 * the first path segment is their uid). The Server Action only ever handles
 * metadata.
 *
 * ## Why TUS rather than a plain PUT
 *
 * Resumability. A 47 MB deck on a lecture-hall connection is a transfer that
 * genuinely gets interrupted, and a plain upload restarts from zero every time.
 * TUS checkpoints server-side, so a retry continues from where it stopped.
 * `tus-js-client` also reports per-chunk progress, which is what the dialog's
 * progress bar reads.
 *
 * ⚠ `chunkSize` must be exactly 6 MB. Supabase's resumable endpoint rejects any
 * other value — this is not a performance knob, and a "sensible" 1 MB or 10 MB
 * makes the upload fail partway through with a size error.
 */

/** Progress from 0 to 1. */
export type UploadProgress = (fraction: number) => void;

export class UploadCancelledError extends Error {
  constructor() {
    super("Upload cancelled.");
    this.name = "UploadCancelledError";
  }
}

/**
 * The Content-Type the upload DECLARES to Storage.
 *
 * `storage.buckets.allowed_mime_types` (migration `20260720213501`) checks the DECLARED
 * type, not the bytes — and some pickers report `File.type` as `""` for a `.pptx` the
 * dialog's extension-based `accept` filter happily allowed (Windows without Office
 * installed, some Linux MIME registries). Falling back to `application/octet-stream`
 * there would have Storage refuse a file the pipeline's byte-sniffing validator would
 * accept, surfaced as a misleading "check your connection" error. So the fallback is
 * derived from the extension the picker filtered on; the byte-level verdict still
 * belongs to `validateDocument`, which reads the stored bytes and corrects
 * `documents.mime_type` afterwards. An unknown extension with no type keeps the honest
 * `application/octet-stream` and lets the bucket refuse it — that path never carried
 * bytes the pipeline could read.
 */
export function declaredContentType(file: {
  readonly name: string;
  readonly type: string;
}): string {
  if (file.type !== "") return file.type;
  const name = file.name.toLowerCase();
  if (name.endsWith(".pdf")) return DOCUMENT_MIME_TYPES.pdf;
  if (name.endsWith(".pptx")) return DOCUMENT_MIME_TYPES.pptx;
  return "application/octet-stream";
}

/**
 * sha256 of the file as lowercase hex — `documents.content_hash`, and the key
 * `documents_dedupe` compares.
 *
 * Plain sha256 over the raw bytes: no normalisation, no framing, nothing clever.
 * The digest's only job is to be identical for identical files, and any
 * cleverness here is a way for two call sites to disagree.
 *
 * Reads the whole file into memory, which is safe **because the size check has
 * already run**. `validateDocumentSize` rejects anything over 50 MB before this
 * is ever called, so the largest allocation this can make is 50 MB — fine in any
 * browser that can open the file at all. The ordering is load-bearing, not
 * incidental: hashing first would mean pulling a 164 MB textbook into a tab in
 * order to discover it was too large.
 */
export async function hashFile(file: File): Promise<string> {
  const digest = await crypto.subtle.digest("SHA-256", await file.arrayBuffer());
  return Array.from(new Uint8Array(digest))
    .map((byte) => byte.toString(16).padStart(2, "0"))
    .join("");
}

export interface TusUploadInput {
  readonly file: File;
  readonly userId: string;
  readonly courseId: string;
  readonly documentId: string;
  readonly onProgress?: UploadProgress;
  readonly signal?: AbortSignal;
}

/**
 * Uploads the file to `{user}/{course}/{document}/{filename}` and resolves with
 * the storage path it wrote.
 *
 * The document id is generated by the CALLER, before this runs, because the path
 * embeds it — see `paths.ts` for why that ordering is forced rather than chosen.
 */
export async function uploadToStorage(input: TusUploadInput): Promise<string> {
  const supabase = createClient();
  const {
    data: { session },
  } = await supabase.auth.getSession();

  if (!session) {
    throw new Error("Your session expired. Sign in again and retry the upload.");
  }

  const objectName = [
    input.userId,
    input.courseId,
    input.documentId,
    safeStorageFilename(input.file.name),
  ].join("/");

  return new Promise<string>((resolve, reject) => {
    const upload = new Upload(input.file, {
      endpoint: `${env.NEXT_PUBLIC_SUPABASE_URL}/storage/v1/upload/resumable`,
      retryDelays: [0, 1000, 3000, 5000],
      headers: {
        authorization: `Bearer ${session.access_token}`,
        // Refuse to overwrite. The path contains a freshly generated uuid, so an
        // object already sitting there means something is badly wrong, and
        // silently replacing it would be the wrong response to that.
        "x-upsert": "false",
      },
      uploadDataDuringCreation: true,
      removeFingerprintOnSuccess: true,
      metadata: {
        bucketName: DOCUMENTS_BUCKET,
        objectName,
        contentType: declaredContentType(input.file),
        cacheControl: "3600",
      },
      // ⚠ Exactly 6 MB. Not a tunable — see the header comment.
      chunkSize: TUS_CHUNK_BYTES,
      onError: reject,
      onProgress: (sent, total) => {
        input.onProgress?.(total === 0 ? 1 : sent / total);
      },
      onSuccess: () => resolve(objectName),
    });

    input.signal?.addEventListener("abort", () => {
      void upload.abort(true);
      reject(new UploadCancelledError());
    });

    // Resume a previous attempt at this exact path when one is on record — the
    // entire reason for choosing TUS.
    void upload.findPreviousUploads().then((previous) => {
      const first = previous[0];
      if (first) upload.resumeFromPreviousUpload(first);
      upload.start();
    });
  });
}
